---
# tasks file for openshift-networkbridge 
- name: Creating a Linux bridge network attachment definition in named namespace
  kubernetes.core.k8s:
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: "bridge-{{ openshift_networkbridge_bridge_interface }}"
        namespace: "{{ openshift_networkbridge_namespace }}"
        annotations:
          k8s.v1.cni.cncf.io/resourceName: "bridge.network.kubevirt.io/{{ openshift_networkbridge_bridge_interface }}"
      spec:
        config:
          cniVersion: 0.3.1
          name: bridge-{{ openshift_networkbridge_bridge_interface }}
          type: cnv-bridge
          bridge: {{ openshift_networkbridge_bridge_interface }}