---
# tasks file for openshift-networkbridge 
- name: Creating a Linux bridge network attachment definition in named namespace
  kubernetes.core.k8s:
    api_key: "{{ api_key }}"
    state: present
    template: "bridge-network-attachement-definition.yaml.j2"